routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('boat','BoatController');

app/Boat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Boat extends Model
{
    protected $fillable = ['nameBoat', 'price', 'cidade', 'boatSize', 'boatDescription'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BoatController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Boat;
class BoatController extends Controller
{
   
    public function index()
    {
        $boats = Boat::latest()->paginate(5);
        return view('boat.index',compact('boats'))
                    ->with('i',(request()->input('page',1)-1)*5);
    }

    
    public function create()
    {
        return view('boat.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'nameBoat' => 'required',
            'price' => 'required',
            'cidade' => 'required',
            'boatSize' => 'required',
            'boatDescription' => 'required'
        ]);  
        Boat::create($request->all());
        return redirect()->route('boat.index')
                        ->with('success','new boat created sucessfully'); 
    }

    
    public function show($id)
    {   
        $boat=Boat::find($id);
        return view('boat.detail',compact('boat'));
    }

    
    public function edit($id)
    {
        $boat=Boat::find($id);
        return view('boat.edit',compact('boat'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'nameBoat' => 'required',
            'price' => 'required',
            'cidade' => 'required',
            'boatSize' => 'required',
            'boatDescription' => 'required'
        ]);

        $boat=Boat::find($id);
        $boat->nameBoat=$request->get('nameBoat');
        $boat->price=$request->get('price');
        $boat->cidade=$request->get('cidade');
        $boat->boatSize=$request->get('boatSize');
        $boat->boatDescription=$request->get('boatDescription');
        $boat->save();
        return redirect()->route('boat.index')
                        ->with('success','Boat update successfully');
    }

    
    public function destroy($id)
    {
        $boat=Boat::find($id);
        $boat->delete();
        return redirect()->route('boat.index')
                         ->with('success','Boat deleted successfully');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/boat/create.blade.php
@extends('layouts.app')
@section('content')
    <div  class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>New boat</h3>
            </div>
        </div>
        @if($errors->any())
            <div class="alert alert-danger">
                <strong>Error!</strong>There where some problems with your input.
                <ul>
                    @foreach($errors as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{route('boat.store')}}" method="post">
        @csrf
            <div class="row"> 
                <div class="col-md-12"> 
                    <strong>Name Boat:</strong>
                    <input type="text" name="nameBoat" class="form-control" placeholder="Name Boat">
                </div>
                <div class="col-md-4"> 
                    <strong>Price:</strong>
                    <input type="number" name="price" class="form-control" placeholder="Price of Boat">
                </div>
                <div class="col-md-4"> 
                    <strong>City: </strong>
                    <input type="text" name="cidade" class="form-control" placeholder="City">
                </div>
                <div class="col-md-4"> 
                    <strong>Size Boat(pés): </strong>
                    <input type="number" name="boatSize" class="form-control" placeholder="Size Boat">
                </div>
                <div class="col-md-12"> 
                    <strong>Boat Description</strong>
                    <textarea class="form-control" placeholder="Description" name="boatDescription"></textarea>
                </div>
                <div class="col-md-12">
                    <a href="{{route('boat.index')}}" class="btn btn-sm btn-success">Back</a>
                    <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                </div>
            <div>
        </form>
    </div>

@endsection

resources/views/boat/detail.blade.php
@extends('layouts.app')
@section('content')
    <div class="container"> 
        <div class="row">
            <div class="col-md-12">
                <h3>About boat</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <strong>Name Boat: </strong> {{$boat->nameBoat}}
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <strong>Price:</strong> R$ {{$boat->price}}
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <strong>City: </strong> {{$boat->cidade}}
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <strong>Boat Size: </strong> {{$boat->boatSize}} pés
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <strong>Boat Description: </strong> {{$boat->boatDescription}}
                </div>
            </div>
            <div class="col-md-12">
                <a href="{{route('boat.index')}}" class="btn btn-sm btn-success">Back</a>
            </div>
    </div>

@endsection

resources/views/boat/edit.blade.php
@extends('layouts.app')
@section('content')
    <div  class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>Update Boat</h3>
            </div>
        </div>
        @if($errors->any())
            <div class="alert alert-danger">
                <strong>Error!</strong>There where some problems with your input.
                <ul>
                    @foreach($errors as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{route('boat.update',$boat->id)}}" method="post">
        @csrf
        @method('PUT')
            <div class="row"> 
                <div class="col-md-12"> 
                    <strong>Name Boat:</strong>
                    <input type="text" name="nameBoat" class="form-control" value="{{$boat->nameBoat}}">
                </div>
                <div class="col-md-4"> 
                    <strong>Price:</strong>
                    <input type="number" name="price" class="form-control" value="{{$boat->price}}">
                </div>
                <div class="col-md-4"> 
                    <strong>City: </strong>
                    <input type="text" name="cidade" class="form-control" value="{{$boat->cidade}}">
                </div>
                <div class="col-md-4"> 
                    <strong>Size Boat(pés): </strong>
                    <input type="number" name="boatSize" class="form-control" value="{{$boat->boatSize}}">
                </div>
                <div class="col-md-12"> 
                    <strong>Boat Description</strong>
                    <textarea class="form-control" name="boatDescription" >{{$boat->boatDescription}}</textarea>
                </div>
                <div class="col-md-12">
                    <a href="{{route('boat.index')}}" class="btn btn-sm btn-success">Back</a>
                    <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                </div>
            <div>
        </form>
    </div>

@endsection

resources/views/boat/index.blade.php
@extends('layouts.app')
@section('content')

<div class="container"> 
    <div class="row">
        <div class="col-md-10">
            <h3> List Boats </h3>
        </div>
        <div class="col-sm-2">
            <a class="btn btn-sm btn-success" href="{{ route('boat.create') }}">Create New Boat</a>
        </div>
    </div>
@if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p> {{$message}}</p>
    </div>
@endif
    <div class="table-responsive-md">
        <table class="table">
            <thead>
                <tr>
                    <th><b>N.</b></th>
                    <th>Nome</th>
                    <th>Price</th>
                    <th>City</th>
                    <th>Boat Size</th>
                    <th>Boat Description</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>

                @foreach ($boats as $boat)
                <tr>
                    <td><b>{{++$i}}.</b></td>
                    <td>{{$boat->nameBoat}}</td>
                    <td>{{$boat->price}}</td>
                    <td>{{$boat->cidade}}</td>
                    <td>{{$boat->boatSize}}</td>
                    <td>{{$boat->boatDescription}}</td>
                    <td>
                        <form  action="{{route('boat.destroy',$boat->id)}}" method="post">
                            <a class="btn btn-sm btn-success"href="{{route('boat.show',$boat->id)}}">Show</a>
                            <a class="btn btn-sm btn-warning"href="{{route('boat.edit',$boat->id)}}">Edit</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            <tbody>
        </table>
        {!!$boats->links()!!}
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Teste') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'RBarcos') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Registrar') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Sair') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>